export const audio_data = [
  {
    id: 1,
    image: '',
    name: 'Micheal Scott',
    username: '@mscott',
    added_time: 'just now',
    title: 'Why are we here, where are we going?',
    isPlaying: false,
    hasTimer: false,
    isTagged: true,
    isLiked: false,
    time: '00:54',
  },
  {
    id: 2,
    image: '',
    name: 'Pam Beesley',
    username: '@pamb',
    added_time: 'just now',
    title: 'I love inside jokes. I hope to be a part of one someday!',
    isPlaying: true,
    hasTimer: true,
    isTagged: false,
    isLiked: false,
    time: '01:30',
  },
  {
    id: 3,
    image: '',
    name: 'Jim Halpert',
    username: '@jhalpert',
    added_time: 'just now',
    title: '',
    isPlaying: true,
    hasTimer: false,
    isTagged: false,
    isLiked: true,
    time: '01:23',
  },
  {
    id: 4,
    image: '',
    name: 'Pam Beesley',
    username: '@pamb',
    added_time: 'just now',
    title: 'I love inside jokes. I hope to be a part of one someday!',
    isPlaying: false,
    hasTimer: false,
    isTagged: false,
    isLiked: false,
    time: '01:30',
  },
];
